// angular/path-location-strategy/src/app/views/about/about.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "about",
  template: `
    <div>
      <h1>About</h1>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate
        maiores incidunt aliquid sequi expedita qui, nostrum eum minus, harum
        inventore blanditiis optio sit tempora atque voluptas quos. Ad, itaque
        voluptas.
      </p>
      <button
        click="$lyticus.trackClick('cyan-button')"
        style="background: cyan"
      >
        Cyan button
      </button>
    </div>
  `
})
export class AboutViewComponent {}

// nuxt/static/pages/about.vue
<template>
  <div>
    <h1>About</h1>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate maiores
      incidunt aliquid sequi expedita qui, nostrum eum minus, harum inventore
      blanditiis optio sit tempora atque voluptas quos. Ad, itaque voluptas.
    </p>
    <button
      @click="$lyticus.trackClick('cyan-button')"
      style="background: cyan"
    >
      Cyan button
    </button>
  </div>
</template>
